# Generated by Django 5.2 on 2025-05-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_otp_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
