# Generated by Django 5.2 on 2025-05-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_image_url_profile_image_url_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
    ]
